name: "TFTP server"
description: "tftp server for ios backups"
version: "1.0.3"
slug: "tftp"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

map: ["share:rw"]

ports:
  69/udp: 69
